<?php
namespace Antheia\Antheia\Classes\AppMenu;
use Antheia\Antheia\Classes\AbstractClass;
use Antheia\Antheia\Classes\Exception;
use Antheia\Antheia\Classes\Globals;
use Antheia\Antheia\Classes\Internals;
use Antheia\Antheia\Classes\Icon\AbstractIcon;
use Antheia\Antheia\Classes\Icon\IconPixelBig;
use Antheia\Antheia\Classes\Icon\IconVector;
use Antheia\Antheia\Interfaces\HtmlCode;
use Antheia\Antheia\Interfaces\HtmlId;
/**
 * A menu item from the main menu of the page (the sliding one on the left
 * side of the page)
 * @author Cosmin Staicu
 */
class AppMenuPrimary extends AbstractClass implements HtmlCode, HtmlId {
	/** @var AbstractIcon */
	private $icon;
	private $text;
	private $href;
	private $submenus;
	private $startLoadingAnimation;
	private $htmlId;
	private $testId;
	public function __construct() {
		$this->icon = new IconPixelBig();
		$this->text = 'undefined';
		$this->setHref('#');
		$this->submenus = [];
		$this->startLoadingAnimation = Globals::getAppMenuLoadingAnimation();
		$this->htmlId = '';
		$this->testId = '';
	}
	public function setHtmlId(string $id):void {
		$this->htmlId = $id;
	}
	public function setTestId(string $id):void {
		$this->testId = $id;
	}
	/**
	 * Defines if a loading animation will be triggered when the user clicks
	 * on this menu. If the menu contains submenus then this method is ignored
	 * (a menu with submenus will never show a loading animation on click)
	 * @param boolean $status true if the animation will start, false if not
	 */
	public function startLoadingOnClick(bool $status):void {
		$this->startLoadingAnimation = $status;
	}
	/**
	 * Defines the href for the menu link. If the menu contains submenus then
	 * this method is ignored, as a specific action is triggered for showing
	 * submenus
	 * @param string $href the location to be loaded on click
	 */
	public function setHref(string $href):void {
		$this->href = $href;
	}
	/**
	 * Returns the submenu list for this menu
	 * @return AppMenuSecondary[] a list with all defined submenus for
	 * this menu
	 */
	public function getSubmenus():array {
		return $this->submenus;
	}
	/**
	 * Adds a submenu item to this menu
	 * @param AppMenuSecondary $submenu the submenu item to be added
	 * to the menu or NULL if a submenu needs to be generated by the library
	 * @return AppMenuSecondary the added menu
	 */
	public function addSubmenu(AppMenuSecondary $submenu = NULL):AppMenuSecondary {
		if ($submenu === NULL) {
			$submenu = new AppMenuSecondary();
		}
		$this->submenus[] = $submenu;
		return $submenu;
	}
	/**
	 * Defines the icon for the menu.
	 * @param AbstractIcon $icon the icon for the menu
	 */
	public function setIcon(AbstractIcon $icon):void {
		$this->icon = $icon;
	}
	/**
	 * Defines the name of the icon for the menu (and, optionally, the icon type)
	 * @param string $name the name of the icon for the menu (the filename of
	 * the symbol, inside the zip file located in the media folder)
	 * @param string [$type=NULL] the type of the icon, as one of the variables
	 * AbstractIcon::PIXEL or AbstractIcon::VECTOR. If no type is provided then
	 * the current icon instance is used (default AbstractIcon::PIXEL).
	 * If type is provided then a new instance for the icon will be created
	 */
	public function setIconName(string $name, string $type = NULL) {
		if ($type !== NULL) {
			switch ($type) {
				case AbstractIcon::PIXEL:
					$this->setIcon(new IconPixelBig($name));
					break;
				case AbstractIcon::VECTOR:
					$this->setIcon(new IconVector($name));
					break;
				default:
					throw new Exception('Invalid type '.$type);
			}
		} else {
			$this->icon->setIcon($name);
		}
	}
	/**
	 * Returns the icon linked to the menu (placed on the left side of the menu)
	 * @return AbstractIcon the icon linked to the menu
	 */
	public function getIcon() {
		return $this->icon;
	}
	/**
	 * Defines the text to be displayed on the menu
	 * @param string $text the text to be displayed on the menu
	 */
	public function setText(string $text):void {
		$this->text = $text;
	}
	public function getHtml():string {
		$code = '';
		if (count($this->submenus) === 0) {
			$code .= '<a href="'.$this->href.'" ';
		} else {
			$code .= '<button type="button"';
		}
		$code .= Internals::getHtmlIdCode($this->htmlId, $this->testId);
		if (count($this->submenus) === 0) {
			if ($this->startLoadingAnimation) {
				$code .= ' onClick="ant_loading_start()"';
			}
		} else {
			$code .= ' onClick="ant_appMenu_toggleSubmenu(this)"';
		}
		$code .= '>'.$this->icon->getHtml($this->text).' '.htmlspecialchars($this->text);
		if (count($this->submenus) === 0) {
			$code .= '</a>';
		} else {
			$code .= '</button><div>';
			/** @var AppMenuSecondary $item */
			foreach ($this->submenus as $item) {
				$code .= $item->getHtml();
			}
			$code .= '</div>';
		}
		return $code;
	}
}
