<?php
namespace Antheia\Antheia\Classes\Accordion;
use Antheia\Antheia\Classes\AbstractClass;
use Antheia\Antheia\Classes\Exception;
use Antheia\Antheia\Classes\Icon\IconVector;
use Antheia\Antheia\Interfaces\HtmlCode;
use Antheia\Antheia\Classes\Globals;
use Antheia\Antheia\Classes\Internals;
/**
 * The class defines an accordion item. The item can be clicked, to be expanded
 * and show some content
 * WARNING! The class should not be directly instanced. A new instance can
 * be generated by callind the method getNewItem() from the container instance
 * @author Cosmin Staicu
 *
 */
class Item extends AbstractClass implements HtmlCode {
	private $triggerId;
	private $triggerTestId;
	private $contentId;
	private $contentTestId;
	private $title;
	private $list;
	/**
	 * The class should not be directly constructed. A new instance can
	 * be generated by calling the method getNewItem() from the container instance
	 * @throws Exception
	 */
	public function __construct() {
		parent::__construct();
		$this->triggerId = '';
		$this->triggerTestId = '';
		$this->contentId = '';
		$this->contentTestId = '';
		$this->title = 'Undefined';
		$this->list = [];
	}
	/**
	 * Defines the html id for the trigger (the button that toogles the content)
	 * @param string $id the html id for the trigger or an empty string
	 * if no id is required
	 */
	public function setTriggerHtmlId(string $id):void {
		$this->triggerId = $id;
	}
	/**
	 * Defines the html test id for the trigger (the button that toogles the content)
	 * @param string $id the html test id for the trigger or an empty string
	 * if no id is required
	 * @see Globals::setTestMode();
	 */
	public function setTriggerHtmlTestId(string $id):void {
		$this->triggerTestId = $id;
	}
	/**
	 * Defines the html id for the content
	 * @param string $id the html id for the content or an empty string
	 * if no id is required
	 */
	public function setContentHtmlId(string $id):void {
		$this->contentId = $id;
	}
	/**
	 * Defines the html test id for the content
	 * @param string $id the html test id for the content or an empty string
	 * if no id is required
	 * @see Globals::setTestMode();
	 */
	public function setContentHtmlTestId(string $id):void {
		$this->contentTestId = $id;
	}
	/**
	 * Defines the title of the item. The title can contain html code, as it
	 * will be inserted as it is (function htmlspecialchars() is not called)
	 * @param string $title the title of the item
	 */
	public function setTitle($title):void {
		$this->title = $title;
	}
	/**
	 * Add some element that will be inserted into the list that will be visible
	 * when the item is expandes
	 * @param HtmlCode $item the element that will be added to the item
	 */
	public function addElement(HtmlCode $item):void {
		$this->list[] = $item;
	}
	public function getHtml():string {
		// start head
		$code = '<button onClick="ant_accordion_click(this)" type="button"'
			.Internals::getHtmlIdCode($this->triggerId, $this->triggerTestId)
			.'>';
		$code .= '<span>'.(new IconVector('arrow-down'))->getHtml().'</span>';
		$code .= '<span>'.(new IconVector('arrow-up'))->getHtml().'</span>';
		$code .= $this->title.'</button>';
		$code .= '<div'
			.Internals::getHtmlIdCode($this->contentId, $this->contentTestId)
			.'>';
		/** @var HtmlCode $element */
		foreach ($this->list as $item) {
			$code .= $item->getHtml();
		}
		$code .= '</div>';
		return $code;
	}
}
?>